In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import time

# DTW package: 
from dtaidistance import dtw

In [3]:
data = pd.read_csv("../data/preprocessed_data.csv")
data.head()

,Unnamed: 0,timestamp,load_Rotary_C5_temp,execution,program_name,nsequence,cr,index
0,46,2024-03-11 14:01:19.408233,0.014493,0,O0005(5303-005-C),N10,CR-1,0
1,49,2024-03-11 14:01:29.432814,0.014493,0,O0005(5303-005-C),N10,CR-1,1
2,63,2024-03-11 14:01:37.451878,0.000000,0,O0005(5303-005-C),N10,CR-1,2
3,64,2024-03-11 14:01:44.468672,0.000000,0,O0005(5303-005-C),N10,CR-1,3
4,78,2024-03-11 14:01:52.489886,0.000000,0,O0005(5303-005-C),N10,CR-1,4

In [4]:
req_data = data.copy()

In [ ]:
req_data = req_data[['timestamp', 'cr', 'load_Rotary_C5_temp']]

req_data.head()

                    timestamp    cr  load_Rotary_C5_temp
0  2024-03-11 14:01:19.408233  CR-1             0.014493
1  2024-03-11 14:01:29.432814  CR-1             0.014493
2  2024-03-11 14:01:37.451878  CR-1             0.000000
3  2024-03-11 14:01:44.468672  CR-1             0.000000
4  2024-03-11 14:01:52.489886  CR-1             0.000000

## Get Load Curves per CR as lists:

In [ ]:
def prepare_sequences_for_dtw(data): 
    start_time = time.time()

    print("===== STEP 1: Preparing Sequences =====")
    grouped = data.groupby('cr')['load_Rotary_C5_temp'].apply(list)
    cr_load_curves = grouped.tolist()

    elapsed_time = time.time() - start_time 
    print("Time taken in STEP 1: ", elapsed_time)

    return cr_load_curves

# Get the list of load curves per CR: 
cr_load_curves = prepare_sequences_for_dtw(data)